### ISSUE TITLE
Attempted to call function "apc_fetch" from namespace "Doctrine\Common\Cache".

### ISSUE THREAD

**Issue by matt-halliday** [sulu/SuluFormBundle#97]
Sulu version: 1.6.3
PHP version: 7.1
Symfony version: 3.3.8
Symfony environment: prod
DoctrineCache version: 1.7.1
Form Bundle version: Symfony 3 PR

May be something, may be nothing but in production with the following Sulu config:
```
doctrine:
    orm:
        metadata_cache_driver: apcu
        query_cache_driver: apcu
        result_cache_driver: apcu
```
Upon submitting a form, an error is thrown:
`Attempted to call function "apc_fetch" from namespace "Doctrine\Common\Cache".`

I fixed it by installing a BC APCU extension:

```
$ pecl install pecl/apcu_bc-1.0.3
$ echo "extension=apc.so" > /usr/local/etc/php/conf.d/apcu.ini
```
But I'm not sure why it's being thrown on submitting a form.
